### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by 1024chen** [OliverBrotchie/ob#11]
Why is there no .html for the link inserted into index.html. For example: 
```html
					<!-- OB -->
<li id='90699696897703'><a href='blog/90699696897703'><h3>test</h3><span>by c</span><time datetime='Wed, 17 Nov 2021 00:36:07 +0000'>Wed, 17 Nov 2021</time></a></li>

```

**Comment by OliverBrotchie** [comment]
It isn't necessary in most hosted environments (for example Nginx). Is this causing an issue with yours? If so, I can swap it over to include the file extension.

**Comment by 1024chen** [comment]
Haha, I am using OB, so I have some doubts about it

**Comment by OliverBrotchie** [comment]
Well it's <350 lines of code so if you don't like something, feel free to fork it and make it your own!
